# -*- coding: utf-8 -*-
"""Copy of Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l1h7oyofEsgJuIyswbPSnx7_cYI2YpMH
"""

firstname = input("Enter your First name")
surname = input("Enter your Surname")
age = input("Enter your Age")

add_text = "My name is " + firstname + " " + surname + " and I am " + age + " years old."
print(add_text)



num1 = int(input("Enter a number"))
num2 = int(input("Enter another number"))

add_num = num1 + num2
print(add_num)

num1 = float(input("Enter a number"))
num2 = float(input("Enter another number"))

add_num = num1 - num2
print (round(add_num))

num1 = 9
num2 = 55
print(num1==num2)

height = float(input("Enter Height"))
weight = float(input("Enter Weight"))
result = height/weight * 100 # Not sure what is the Calc_BMI calculation
if (result > 30):
  print("High")
else:
  print("Low")

